spring:
  datasource:
    username: root
    password: admin


    #    password: 1998
#    url: jdbc:mysql://localhost:3306/shenyou?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/shenyou?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver





  #spring session使用存储类型，默认就是redis所以可以省略



mybatis:
  mapper-locations: classpath:org/lanqiao/mapper/*.xml
  type-aliases-package: org.lanqiao.entity
#server:
#  tomcat:
#    max-http-post-size: -1
#showSql
logging:
  level:
    org:
      lanqiao:
        mapper : debug

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


